### ISSUE TITLE
`--reset --tag` takes on the existing logic of `--skip-build --tag`

### ISSUE THREAD

**Issue by consideRatio** [jupyterhub/chartpress#176]
I think the combination of #152 and #150 made `chartpress --reset` more complicated than it should be, because the functionality we ended up with is the same as `chartpress --skip-build` when both are given `--tag`.

Practically, I'm thinking that the commands below are the same.

```
chartpress --reset --tag 1.2.3
chartpress --skip-build --tag 1.2.3
```

Should we revert the logic of `--reset --tag` as implemented via #152 and #150?

Ping to @minrk for visibility, and also #174 is worth a mention from this issue.

**Comment by minrk** [comment]
When removing the feature, is the idea to make `--reset` explicitly conflict with `--tag`, so that you _have_ to use `--skip-build` instead to change the tag? I.e. `--reset` is only ever useful in e.g. a pre-commit hook (automated or manual)?

**Comment by consideRatio** [comment]
My main idea is avoid the introduction of separate logic doing the same thing in `--reset --tag` as in `--skip-build --tag`.

Either by making `--tag` ignored when `--reset` is passed (latest release of chartpress' behavior), or making an error be raised when that happens. In practice, `chartpress --reset` would then mainly have a purpose matching use in a pre-commit hook.

**Comment by minrk** [comment]
I opened the PR because I think the silent ignoring of the tag was a problem, so I'd rather not go back to that. We could raise and print the correct command instead.

I do think `--reset --tag` is _more_ logical than skip build, so I'd also be happy deprecating that in favor of reset.

But let's see how the simplified reset looks after moving baseVersion to chartpress.yaml. I think it's a lot simpler either way.
